api:
  image:
    repository: death-metal-api
    tag: 1.0.0

web:
  image:
    repository: death-metal-web
    tag: 1.0.0

configmap:
  name: api-config1.1
  data:
    ENV_TITLE: "-"

ingress:
  className: nginx
  host: ""