applications:
  death-metal-dev:
    namespace: argocd
    project: default
    source:
      repoURL: https://github.com/venelin-genadiev/demo-helm-app
      path: app
      targetRevision: main
      helm:
        valueFiles:
          - values.yaml
          - values-dev.yaml
    destination:
      server: https://kubernetes.default.svc
      namespace: dev
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - CreateNamespace=true

  death-metal-prod:
    namespace: argocd
    project: default
    source:
      repoURL: https://github.com/venelin-genadiev/demo-helm-app
      path: app
      targetRevision: main
      helm:
        valueFiles:
          - values.yaml
          - values-prod.yaml
    destination:
      server: https://kubernetes.default.svc
      namespace: prod
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - CreateNamespace=true
