apiVersion: apps/v1
kind: Deployment
metadata:
  name: death-metal-api
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/instance: death-metal-api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
      maxSurge: 1 ## not more than 3 (save resources)
  template:
    metadata:
      labels:
        app.kubernetes.io/name: death-metal
        app.kubernetes.io/component: backend
        app.kubernetes.io/instance: death-metal-api
    spec:
      containers:
      - name: death-metal-api
        image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}"
        livenessProbe: ## should continer be restarted
          httpGet:
            path: /liveness
            port: 3005
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 3
        readinessProbe: ## should container be ready to serve traffic
          httpGet:
            path: /readiness
            port: 3005
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 3
        envFrom:
        - configMapRef:
            name: {{ .Values.configmap.name }}
        - secretRef:
            name: api-secret
        resources:
          requests:
            memory: "128Mi"
            cpu: "128m"
          limits:
            memory: "128Mi"
        ports:
        - containerPort: 3005

