apiVersion: v1
kind: Service
metadata:
  name: death-metal-api-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app.kubernetes.io/instance: death-metal-api
  ports:
  - port: 3005
    targetPort: 3005
