apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: death-metal-web-ingress
  namespace: death-metal
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: /death-metal-groups
        backend:
          service:
            name: death-metal-api-service
            port:
              number: 3005
      - pathType: Prefix
        path: /
        backend:
          service:
            name: death-metal-web-service
            port:
              number: 8080
